name: proc-chain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - cartopy
  - matplotlib
  - scipy
  - xarray
  - netcdf4
  - pyyaml
  - cdsapi
  - scikit-learn
  - f90nml
  - sphinx
  - sphinx_rtd_theme
  - sphinx-copybutton
  - pip
  - pip:
    - icoscp
    - requests
    - urllib3
    - certifi